### ISSUE TITLE
整理开户攻略

### ISSUE THREAD

**Issue by observerss** [observerss/ybk#11]
正好还有很多户没有开

- [x] 一边申请一遍整理一个开户攻略
- [x] 整理交易所的, 开户链接, 资料列表, 可用银行，银行绑定方式，etc
- [x] 整理交易所的账号开户攻略
- [x] 整理银行的银商绑定攻略
- [x] 整理出入金和申购攻略

**Comment by popsars** [comment]
让用户把所有资料传上来,然后搞个一键开户,帮他把所有的交易所都开好.这个应该很不错.
先去注册个经纪会员

**Comment by popsars** [comment]
注意工商银行开一张理财金卡(没任何要求)就可以享受2折网银和手机银行转帐手续费
农行用K宝后,手机银行转帐可以打3折,网银不打折
建行手机银行和网银都是单笔1元

工商银行建议购买通用U盾(70元)
农业银行K宝(50元)
建设银行网银盾(18元?)

建行的手机银行转帐默认限额是单笔20w单日20w,到柜台可以填表提升至最高单笔500w单日500w
建行的网上银行转帐默认限额是单笔500w单日500w,到柜台可以填表提升至自定义
回头会有95533打电话和你确认信息,然后再审核,可能过也可能不过,但无论过还是不过都不会通知你,要自己去申请提高限额的银行去问,95533是查不到的.

农行好像默认转帐限额是100w,但可以去柜台随便提升,当场生效.

农行好像默认转帐限额是100w,但可以去柜台随便提升,500w以下当场生效.超过的话要去分行审批.
