### ISSUE TITLE
抓取整合各大交易所的行情

### ISSUE THREAD

**Issue by observerss** [observerss/ybk#13]
- [x] 用@popsars的代码每隔1小时更新一次交易所行情
- [x] 整合一个web下方便地看K线/日内的行情浏览模块
- [x] 生成页面追踪打新收益(需要用户登陆并记录持仓, 交易)
- [ ] 和中签率结合搜索最优打新算法
- [ ] 调查是否可以整合交易操作(出入金+买卖+查询)

**Comment by popsars** [comment]
前面测了一下所有客户端的行情请求,共分为两类
第一类是http请求,第二类是tcp请求

对于第一类
Site	南交所	http://180.97.2.67:19914
	江苏所	http://180.96.20.219:16844
	金马甲	http://jyqz.jinmajia.com:16914
	福丽特	http://tradeweb1.dzp.wjybk.com:16914
	华夏所	http://218.249.27.82:20504
	南方所	http://183.6.187.34:19914
	中南所	http://180.97.2.112:15914
	华中所	http://61.183.138.62:19914
	中融所	http://115.182.221.15:16964
	宁夏所	http://122.96.106.44:9014
	华强所	http://180.96.50.179:16914
获取商品列表	/hqApplet/data/CreateXMLClass.xml
获取日线数据	/hqApplet/data/day/00100001.day.zip
获取1分钟数据	/hqApplet/data/min/00100001.min.zip
实时行情是post,单开issue说明

其中00100001的前两位00代表CreateXMLClass.xml中对应品种的market,后六位代表cc_commodity_id
zip包解压后需要解析bin文件,交给你了,应该不麻烦

对于第二类
Site	上邮所
	上海所
	海西所
	湖南所
还没空去搞,还要搞tcp估计很麻烦

**Comment by observerss** [comment]
后三个需求单独开Issue
